tab_spaces = 2
trailing_comma = "Vertical"
max_width = 120
edition = "2024"
reorder_imports = true
reorder_impl_items = true
reorder_modules = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"